// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var pgpu;

  pgpu = require('pgp-utils');

  exports.checker = function(setter) {
    if (setter == null) {
      setter = null;
    }
    return function(x) {
      var err, res, _ref;
      _ref = pgpu.armor.decode(x), err = _ref[0], res = _ref[1];
      if ((err == null) && (res != null) && (setter != null)) {
        setter(res);
      }
      return err;
    };
  };

}).call(this);
